version: '3.8'

services:
  
  dbcpp:
    image: postgres:13
    restart: always
    container_name: dbcpp
    env_file: ./.env
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./db_setup:/db_setup
    command: /bin/sh -c  "cd db_setup && chmod +x db_entry.sh && ./db_entry.sh"
    networks:
      - services


  cppbot:
    image: valeevilja/cppbot:v2
    container_name: cppbot
    restart: always
    ports:
      - 8080:8080
    env_file:
      - ./.env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BASE_WEBHOOK_URL=${BASE_WEBHOOK_URL}
      - ADMIN_CHAT_ID=${ADMIN_CHAT_ID}
    volumes:
      - ./:/cppbot
    networks:
      - services 
    depends_on:
      - dbcpp


  swag:
    image: linuxserver/swag:2.4.0
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - URL=iljavaleev.hopto.org
    env_file:
      - ./.env
    volumes:
      - ./logs/nginx:/var/log/nginx/
      - ./swag_nginx.conf:/config/nginx/site-confs/default.conf
      - keys:/config/keys/
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    networks:
      - services
    depends_on:
      - cppbot

volumes:
  keys:

networks:
  services: